#!/bin/sh

CWD=`dirname $0`
JAVA_OPTS="-Dgetconfig_home=$CWD -Dlogback.configurationFile=$CWD/config/logback.xml"
java $JAVA_OPTS -jar $CWD/build/libs/gradle-server-acceptance-0.1.9-all.jar $1 $2 $3 $4 $5 $6 $7 $8 $9 ${10} ${11} ${12} ${13} ${14} ${15}
