# gem 'ajax-datatables-rails', '0.1.2'
# gem 'jquery-datatables-rails'
gem "kaminari"
# gem 'kaminari', '~> 0.17.0'

group :development do
  # 高機能コンソール
  gem 'pry-rails'

  # デバッガー
  gem 'pry-byebug'
  gem 'pry-stack_explorer'

  # pryの入出力に色付け
  gem 'pry-coolline'
  gem 'awesome_print'

  # PryでのSQLの結果を綺麗に表示
  gem 'hirb'
  gem 'hirb-unicode'
end
